# Generated by Django 6.1 on 2026-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "internal_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
        ),
    ]
