# Generated by Django 6.1 on 2026-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_article_cover_article_parent_article_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
