# Generated by Django 6.1 on 2026-08-15 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("user_repr", models.CharField(default="system", max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("BULK_CREATE", "Création en masse"),
                            ("BULK_UPDATE", "Modification en masse"),
                            ("CUSTOM", "Action personnalisée"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("endpoint", models.CharField(blank=True, default="", max_length=255)),
                (
                    "http_method",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="forge_log_a_content_c79928_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-timestamp"],
                        name="forge_log_a_content_8187b3_idx",
                    ),
                ],
            },
        ),
    ]
